import { useState } from 'react';
import { Link } from 'react-router-dom';
import { PageContainer } from '../../components/layout/PageContainer.jsx';

const fallbackOffices = [
  { slug: 'pakistan-office', city: 'Pakistan Office', country: 'Pakistan', timezone: 'Asia/Karachi', position: ['68%', '48%'] },
  { slug: 'australia-office', city: 'Australia Office', country: 'Australia', timezone: 'Australia/Sydney', position: ['84%', '75%'] },
  { slug: 'uk-office', city: 'UK Office', country: 'United Kingdom', timezone: 'Europe/London', position: ['48%', '34%'] },
];

export function OfficesSection({ apiOffices = [] }) {
  const [active, setActive] = useState(0);
  const offices = fallbackOffices.map((fallback) => {
    const match = apiOffices.find((office) => office.slug === fallback.slug || office.address?.country?.toLowerCase().includes(fallback.country.toLowerCase()) || office.name?.toLowerCase().includes(fallback.country.split(' ')[0].toLowerCase()));
    return match ? { ...fallback, city: match.name || fallback.city, country: match.address?.country || fallback.country, timezone: match.timezone || fallback.timezone, address: match.address } : fallback;
  });
  return <section className="bg-[#ebe6dc] py-24 sm:py-32"><PageContainer><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Meet us around the world</p><h2 className="display-title">Global thinking. <em className="text-gold-dark">Local presence.</em></h2><div className="mt-10 space-y-2">{offices.map((office, index) => <button onMouseEnter={() => setActive(index)} onFocus={() => setActive(index)} onClick={() => setActive(index)} key={office.country} className={`flex w-full items-center justify-between border-b py-5 text-left transition ${active === index ? 'border-gold text-brand' : 'border-brand/10 text-ink-muted'}`}><span><span className="block font-display text-3xl font-semibold">{office.city}</span><span className="mt-1 block text-xs font-bold uppercase tracking-[.14em]">{office.country}</span></span><span className="text-xs">{office.timezone}</span></button>)}</div><Link to="/contact" className="mt-8 inline-flex items-center gap-3 text-sm font-bold text-brand">Plan an office visit <span className="text-gold-dark">→</span></Link></div><div className="relative min-h-[440px] overflow-hidden rounded-[2rem] bg-brand p-6"><div className="absolute inset-0 opacity-25 [background-image:radial-gradient(circle,rgba(255,255,255,.8)_1px,transparent_1px)] [background-size:18px_18px]" /><svg aria-hidden="true" viewBox="0 0 900 480" className="absolute inset-0 size-full opacity-25" fill="none" stroke="currentColor"><path className="text-gold" strokeWidth="1" d="M70 205c92-74 191-108 301-102 75 4 142 28 194 62 44 29 74 32 122 18 67-20 108-3 143 48M165 350c104-47 191-55 260-26 66 27 118 23 174-13 52-34 106-41 174-15" /></svg>{offices.map((office, index) => <button key={office.city} onClick={() => setActive(index)} aria-label={`${office.city} office`} style={{ left: office.position[0], top: office.position[1] }} className="absolute -translate-x-1/2 -translate-y-1/2"><span className={`absolute inset-0 rounded-full bg-gold transition ${active === index ? 'animate-ping' : 'opacity-0'}`} /><span className={`relative block rounded-full border-4 border-brand transition ${active === index ? 'size-6 bg-gold' : 'size-4 bg-white'}`} /></button>)}<div className="absolute bottom-6 left-6 right-6 rounded-2xl border border-white/10 bg-white/10 p-5 text-white backdrop-blur-xl"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-gold-light">Selected office</p><p className="mt-2 font-display text-4xl font-semibold">{offices[active].city}, {offices[active].country}</p><p className="mt-2 text-sm text-white/55">In-person and remote consultations available.</p></div></div></div></PageContainer></section>;
}
