import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { Modal } from '../../components/ui/Modal.jsx';
import { useSeo } from '../../hooks/useSeo.js';
import { AdminEmpty, AdminError, AdminPageHeader, AdminPanel, adminInputClass, FieldLabel, StatusBadge } from '../components/AdminUi.jsx';
import { createMedia, deleteMedia, getMedia, updateMedia } from '../services/adminApi.js';

const blank = { name: '', type: 'image', url: '', altText: '', storageProvider: 'external' };

export function MediaPage() {
  useSeo({ title: 'Media library', description: 'Manage Nestway images, logos and documents.' });
  const queryClient = useQueryClient();
  const [type, setType] = useState('');
  const [editing, setEditing] = useState(null);
  const [formOpen, setFormOpen] = useState(false);
  const [pendingDelete, setPendingDelete] = useState(null);
  const [values, setValues] = useState(blank);
  const query = useQuery({ queryKey: ['admin', 'media', type], queryFn: () => getMedia({ type: type || undefined, limit: 60 }) });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['admin', 'media'] });
  const saveMutation = useMutation({ mutationFn: (payload) => editing ? updateMedia(editing._id, payload) : createMedia(payload), onSuccess: () => { refresh(); setFormOpen(false); } });
  const deleteMutation = useMutation({ mutationFn: deleteMedia, onSuccess: () => { refresh(); setPendingDelete(null); } });
  useEffect(() => { if (formOpen) setValues(editing ? { name: editing.name, type: editing.type, url: editing.url, altText: editing.altText || '', storageProvider: editing.storageProvider || 'external' } : blank); }, [editing, formOpen]);
  const assets = query.data?.items || [];
  const openCreate = () => { setEditing(null); setFormOpen(true); };
  const openEdit = (asset) => { setEditing(asset); setFormOpen(true); };
  const submit = (event) => { event.preventDefault(); saveMutation.mutate(values); };

  return <div className="space-y-7"><AdminPageHeader eyebrow="Asset foundation" title="Media library" description="Register externally hosted images, logos and documents now, ready for future cloud-storage integration." action={<button type="button" onClick={openCreate} className="rounded-full bg-gold px-5 py-3 text-xs font-bold text-brand">Add asset</button>} /><div className="flex flex-wrap gap-2">{['', 'image', 'logo', 'document'].map((item) => <button key={item || 'all'} type="button" onClick={() => setType(item)} className={`rounded-full px-5 py-2.5 text-xs font-bold capitalize transition ${type === item ? 'bg-brand text-white' : 'border border-brand/10 bg-white text-brand'}`}>{item || 'All media'}</button>)}</div>{(saveMutation.isError || deleteMutation.isError) && <AdminError message={saveMutation.error?.message || deleteMutation.error?.message} />}<AdminPanel className="p-5">{query.isPending ? <div className="p-10 text-center text-sm text-ink-muted">Loading media library…</div> : query.isError ? <AdminError message={query.error?.message} onRetry={() => query.refetch()} /> : assets.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{assets.map((asset) => <article key={asset._id} className="group overflow-hidden rounded-2xl border border-brand/10 bg-[#faf8f3]"><div className="grid aspect-[16/10] place-items-center overflow-hidden bg-brand/5">{asset.type === 'document' ? <span className="font-display text-5xl font-semibold text-gold-dark">PDF</span> : <img src={asset.url} alt={asset.altText || ''} rand className="size-full object-cover" loading="lazy" />}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-bold text-brand">{asset.name}</h2><p className="mt-1 truncate text-xs text-ink-muted">{asset.url}</p></div><StatusBadge status={asset.type} /></div><div className="mt-5 flex gap-2"><a href={asset.url} target="_blank" rel="noreferrer" className="rounded-full border border-brand/12 px-3 py-2 text-xs font-bold">Open</a><button type="button" onClick={() => openEdit(asset)} className="rounded-full border border-brand/12 px-3 py-2 text-xs font-bold">Edit</button><button type="button" onClick={() => setPendingDelete(asset)} className="rounded-full border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Delete</button></div></div></article>)}</div> : <AdminEmpty title="Your media library is ready" description="Add an image, logo or document URL to begin." />}</AdminPanel>
    <Modal isOpen={formOpen} onClose={() => setFormOpen(false)} title={`${editing ? 'Edit' : 'Add'} media asset`}><form onSubmit={submit} className="space-y-5"><FieldLabel label="Asset name *"><input required value={values.name} onChange={(event) => setValues((current) => ({ ...current, name: event.target.value }))} className={adminInputClass} /></FieldLabel><FieldLabel label="Asset type *"><select required disabled={Boolean(editing)} value={values.type} onChange={(event) => setValues((current) => ({ ...current, type: event.target.value }))} className={adminInputClass}>{['image', 'logo', 'document'].map((item) => <option key={item}>{item}</option>)}</select></FieldLabel><FieldLabel label="Public URL *"><input required type="url" value={values.url} onChange={(event) => setValues((current) => ({ ...current, url: event.target.value }))} className={adminInputClass} /></FieldLabel><FieldLabel label="Alternative text"><textarea rows="3" value={values.altText} onChange={(event) => setValues((current) => ({ ...current, altText: event.target.value }))} className={adminInputClass} /></FieldLabel><FieldLabel label="Storage provider"><input value={values.storageProvider} onChange={(event) => setValues((current) => ({ ...current, storageProvider: event.target.value }))} className={adminInputClass} /></FieldLabel>{saveMutation.isError && <AdminError message={saveMutation.error?.message} />}<div className="flex justify-end gap-3 pt-3"><button type="button" onClick={() => setFormOpen(false)} className="rounded-full border border-brand/12 px-5 py-3 text-xs font-bold">Cancel</button><button disabled={saveMutation.isPending} className="rounded-full bg-brand px-6 py-3 text-xs font-bold text-white">{saveMutation.isPending ? 'Saving…' : 'Save asset'}</button></div></form></Modal>
    <Modal isOpen={Boolean(pendingDelete)} onClose={() => setPendingDelete(null)} title="Delete media asset"><p className="leading-7 text-ink-muted">Remove <strong className="text-brand">{pendingDelete?.name}</strong> from the library? The externally hosted file itself will not be deleted.</p><div className="mt-8 flex justify-end gap-3"><button type="button" onClick={() => setPendingDelete(null)} className="rounded-full border border-brand/12 px-5 py-3 text-xs font-bold">Cancel</button><button type="button" onClick={() => deleteMutation.mutate(pendingDelete._id)} className="rounded-full bg-red-700 px-5 py-3 text-xs font-bold text-white">Delete record</button></div></Modal>
  </div>;
}
